/**
 * The `/extension-import` handoff contract.
 *
 * A Chrome extension will one day open this route with one already-detected
 * identifier. That fact does not make the URL trustworthy. Anyone — a web page,
 * an email, a bookmark, an attacker — can construct
 * `https://app.paperlume.app/extension-import?…`, so every value that arrives
 * here is untrusted text and this module fails closed on all of it.
 *
 * ## What may travel in the URL
 *
 * Exactly two parameters, and nothing else is read:
 *
 *   /extension-import?kind=pmid&value=<URL-encoded PMID>
 *   /extension-import?kind=doi&value=<URL-encoded DOI name>
 *
 * No token, no session material, no user id, no Project or Tag id, no title,
 * no abstract, no page content, and no return URL. Projects and Tags are chosen
 * inside authenticated PaperLume against the signed-in user's own RLS-scoped
 * taxonomy, so a foreign id in a query string has nothing to attach itself to.
 *
 * ## No third grammar, and no title fallback
 *
 * Validation delegates to the identifier modules the application already owns —
 * `normalizePmid` and the DOI resolver round trip — rather than restating their
 * rules. And unlike the importer's own classifier, there is deliberately no
 * `title` case: `detectIdentifier()` falls back to a title search because a
 * person pasting into an import box may legitimately be pasting a title, but a
 * handoff parameter is a *machine-supplied identifier*. Text that fails to
 * validate is invalid handoff input, never a search term — `pmid` and `doi` are
 * per-user deduplication keys, so resolving the wrong paper corrupts dedup
 * rather than merely showing something odd.
 *
 * `ExtensionImportIntent` has no title variant at all, which makes the absence a
 * type-level property rather than a convention someone has to remember.
 */

import { canonicalDoiUrl, extractDoiFromDoiUrl } from "@/lib/doiIdentifiers";
import { normalizePmid } from "@/lib/pubmedIdentifiers";

/** The one route that accepts a handoff. */
export const EXTENSION_IMPORT_PATH = "/extension-import";

/**
 * A validated handoff.
 *
 * `identifier` is the exact string that will be handed to the canonical
 * importer — a bare PMID or an unencoded DOI name. Deliberately two cases and
 * no third: see the module comment on the absent title fallback.
 */
export type ExtensionImportIntent =
  | { readonly kind: "pmid"; readonly identifier: string }
  | { readonly kind: "doi"; readonly identifier: string };

/**
 * The per-identifier length the `fetch-paper-metadata` Edge Function itself
 * enforces. Repeated here so an over-long value is refused before it reaches a
 * network call at all, not because this layer is the authority on it.
 */
export const MAX_IDENTIFIER_LENGTH = 500;

/**
 * Validate a PMID supplied as a handoff value.
 *
 * The value must already BE the normalized form. `normalizePmid` trims, so
 * `" 123 "` would normalize to `"123"` — accepting that would silently repair
 * input, and a handoff parameter is generated by software rather than typed by a
 * person, so whitespace means the sender is wrong rather than sloppy. Comparing
 * the normalized result back against the input refuses the repair.
 */
function validatePmid(value: string): string | null {
  const normalized = normalizePmid(value);
  return normalized !== null && normalized === value ? normalized : null;
}

/**
 * Validate a DOI *name* supplied as a handoff value.
 *
 * Proven by round trip through the application's existing DOI grammar rather
 * than by a new pattern:
 *
 *   name --(canonicalDoiUrl)--> canonical doi.org URL --(extractDoiFromDoiUrl)--> name
 *
 * A value survives only if both directions accept it *and* the DOI that comes
 * back is byte-identical to the one that went in. That reuses `10.` directory
 * indicator, registrant code, non-empty suffix, and percent-encoding rules from
 * one place, so this route can never be a weaker third DOI grammar.
 *
 * It also rejects the wrong-direction inputs for free, because `canonicalDoiUrl`
 * refuses a prefix containing `:` — `https://doi.org/10.1000/example` and
 * `doi:10.1000/example` are presentation forms, not DOI names, and a resolver
 * URL supplied where a name is expected must fail rather than be unwrapped.
 */
function validateDoi(value: string): string | null {
  const resolverUrl = canonicalDoiUrl(value);
  if (resolverUrl === null) return null;

  const roundTripped = extractDoiFromDoiUrl(resolverUrl);
  return roundTripped === value ? roundTripped : null;
}

/**
 * Parse a handoff query string into a validated intent.
 *
 * Fails closed on everything: a missing parameter, a repeated one, an unknown
 * kind, an over-long value, and any value the identifier grammar refuses.
 * Repetition is rejected rather than resolved by "first wins" or "last wins",
 * because two different senders disagreeing about the identifier is not a
 * situation this route should pick a winner in.
 *
 * Unrecognised parameters are ignored rather than rejected — a link may pick up
 * tracking parameters in transit — but they can never contribute an identifier,
 * because only `kind` and `value` are ever read.
 *
 * Malformed percent-encoding needs no special case: `URLSearchParams` yields the
 * literal text for a broken escape, which then fails identifier validation.
 *
 * @param search A query string, with or without its leading `?`, or a
 *   `URLSearchParams`.
 * @returns The validated intent, or `null` when the handoff is not valid.
 */
export function parseExtensionImportIntent(
  search: string | URLSearchParams | null | undefined,
): ExtensionImportIntent | null {
  if (search === null || search === undefined) return null;

  const params =
    typeof search === "string" ? new URLSearchParams(search) : search;

  const kinds = params.getAll("kind");
  const values = params.getAll("value");
  if (kinds.length !== 1 || values.length !== 1) return null;

  const kind = kinds[0];
  const value = values[0];

  if (value.length === 0 || value.length > MAX_IDENTIFIER_LENGTH) return null;

  if (kind === "pmid") {
    const pmid = validatePmid(value);
    return pmid === null ? null : { kind: "pmid", identifier: pmid };
  }

  if (kind === "doi") {
    const doi = validateDoi(value);
    return doi === null ? null : { kind: "doi", identifier: doi };
  }

  // Every other kind — including a title, which this route deliberately has no
  // concept of — is invalid handoff input.
  return null;
}

/**
 * Build the canonical handoff path for a validated intent.
 *
 * The inverse of the parser, and the only way a handoff path should ever be
 * produced. It matters most for the sign-in return target: rebuilding the path
 * from validated components means the application never redirects to a string an
 * attacker supplied, only to one it constructed itself.
 */
export function buildExtensionImportPath(intent: ExtensionImportIntent): string {
  const params = new URLSearchParams({
    kind: intent.kind,
    value: intent.identifier,
  });
  return `${EXTENSION_IMPORT_PATH}?${params.toString()}`;
}
