// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { requireClientEnv } from '@/lib/clientEnv';
import type { Database } from './types';

// Fail fast at module load if either required Vite-client env var is
// missing — the upstream `@supabase/supabase-js` error
// (`supabaseUrl is required.`) is opaque and gives a fresh contributor
// no actionable hint about copying `.env.example` to `.env.local`.
const SUPABASE_URL = requireClientEnv('VITE_SUPABASE_URL');
const SUPABASE_PUBLISHABLE_KEY = requireClientEnv('VITE_SUPABASE_PUBLISHABLE_KEY');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});